FROM python:3.12-alpine

WORKDIR /app

# انسخ requirements.txt أولاً
COPY requirements.txt ./

# ثبّت المكتبات
RUN python3 -m pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# انسخ باقي الملفات
COPY Strategy_Engine.py ./
COPY Database.py ./
COPY Order_Block.py ./
COPY telegram_bot.py ./

CMD ["python", "Strategy_Engine.py"]
