# Dockerfile.rust
FROM rust:alpine AS builder

# تثبيت المكتبات الضرورية
RUN apk add --no-cache \
    musl-dev \
    pkgconfig \
    openssl-dev \
    build-base

WORKDIR /app

# نسخ ملفات المشروع
COPY . .

# بناء المشروع في وضع release
RUN cargo build --release

# المرحلة الثانية: صورة تشغيل خفيفة
FROM alpine:latest

WORKDIR /app

# نسخ الباينري فقط من مرحلة البناء
COPY --from=builder /app/target/release/websocket_candle_rust /app/

CMD ["./websocket_candle_rust"]
